from aoc.day6 import parse_input, part1, part2

test_input_part1 = """....#.....
.........#
..........
..#.......
.......#..
..........
.#..^.....
........#.
#.........
......#...
""".splitlines()


def test_part1():
    assert part1(parse_input(test_input_part1)) == 41


def test_part2():
    assert part2(parse_input(test_input_part1)) == 6
